---
title: "Early Vote Analysis for Sunday, Sept. 27"
---

## A Record 944,114 Have Already Voted

After a historic week of early voting in the United States, it is time to take stock of where we are. Sundays are typically a slow day for states to report early voting activity, which gives me a moment to reflect on the prior week.

The headline is the jaw-dropping number of people who have already voted. At least 944,114 people have voted in the 2020 general election. I use the phrase "at least" because the true number is likely higher because I do not have complete reports for all states. Some states currently voting will eventually provide reports, but even among the reporting states some local election offices are clearly lagging on their reporting. An initial reporting delay is common, so there is no cause for concern that something nefarious is afoot. However, in states where early voting statistics are managed at the local level - like Alabama and Missouri - it will require calling local election offices to collect their numbers.

Nearly a million voters this far in advance of an election has never occurred in any American election. Period.

Around this time in 2016, [I noted](https://www.huffpost.com/entry/2016-early-voting-underwa_b_12184290) only 9,525 people had voted.

## Three Factors Accounting for the Dramatic Early Voting Increase

1. **Changing state laws.** For example, Virginia adopted full-fledged in-person early voting for the first time this presidential election. In prior elections, Virginia had a limited form of in-person early voting available to voters with specific excuses. Already, 200,277 Virginians have cast in-person votes, and another 83,822 have voted by mail, thus making Virginia the current leader in raw early votes, a title captured from North Carolina, and will almost assuredly be surrendered to a state like Florida which just sent out a little over 5 million mail ballots to voters.
2. **The pandemic.** Changing state laws cannot be the only explanation. North Carolina did not change its laws, and already 246,615 people have returned their mail ballots and had them accepted for counting. Mail balloting is at unprecedented levels this election cycle due to the pandemic. Nationally, I am tracking over 64 million mail ballots that will been sent to voters. I do not have data yet for all states, so the true number is likely closer to 70 million mail ballot requests. There are two factors driving this unprecedented surge in mail balloting.
  + *Many states are promoting mail balloting.* Some states that formerly had excuse-required absentee voting are allowing social distancing as a valid excuse. Some states that already had high usage of mail balloting - due in part to having permanent absentee ballot lists voters sign up for - transitioned to all-mail ballot elections on a permanent or emergency basis. There are about 44 million voters who will receive a mail ballot in these states.
  + *Voters want to cast mail ballots.* Even in states that have no-excuse absentee voting, the number of mail mail ballot requests are through the roof. Some voters clearly see mail balloting as the safe way to participate in the November election.
3. **Voter interest.** The old adage that you can lead a horse to water but you can't make him drink seems very appropriate. Just because a state provides an early voting option, or sends a voter a mail ballot, does not mean that the voters must vote at the first opportunity to do so. People are making a choice to vote at their first opportunity. The most likely explanation for this phenomenon is Donald Trump. Whether you love him or hate him, he inspires passion unlike any other political figure. Some people have known their preference for president for some time, and are thus expressing it as soon as they can.

