---
title: "Early Vote Analysis for Sunday, Nov. 1"
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(knitr)
library(kableExtra)
library(scales)
library(DT)
library(highcharter)

state_stats <- read_csv("D:/DropBox/Dropbox/Mail_Ballots_2020/markdown/2020G_Early_Vote.csv")

party_shell <- data.frame(Party=character(),
                                  Count=integer(),
                                  Percent=double(),
                                  stringsAsFactors=FALSE)
party_shell[1,1] <- "Democrats"
party_shell[2,1] <- "Republicans"
party_shell[3,1] <- "Minor"
party_shell[4,1] <- "No Party Affiliation"
party_shell[5,1] <- "TOTAL"

party_shell_returned <- data.frame(Party=character(),
                                  Count=integer(),
                                  Frequency=double(),
                                  Count2=integer(),
                                  Rate=integer(),
                                  stringsAsFactors=FALSE)
party_shell_returned[1,1] <- "Democrats"
party_shell_returned[2,1] <- "Republicans"
party_shell_returned[3,1] <- "Minor"
party_shell_returned[4,1] <- "No Party Affiliation"
party_shell_returned[5,1] <- "TOTAL"


US_accept_party <- party_shell_returned

US_accept_party[1,2] <- sum(state_stats$mail_accept_2020_dem) 
US_accept_party[2,2] <- sum(state_stats$mail_accept_2020_rep) 
US_accept_party[3,2] <- sum(state_stats$mail_accept_2020_minor)
US_accept_party[4,2] <- sum(state_stats$mail_accept_2020_npa) 
US_accept_party[5,2] <- sum(state_stats$mail_accept_2020_dem)+sum(state_stats$mail_accept_2020_rep)+sum(state_stats$mail_accept_2020_minor)+sum(state_stats$mail_accept_2020_npa)

US_accept_party[1,4] <- sum(state_stats$mail_sent_req_2020_dem) 
US_accept_party[2,4] <- sum(state_stats$mail_sent_req_2020_rep) 
US_accept_party[3,4] <- sum(state_stats$mail_sent_req_2020_minor)
US_accept_party[4,4] <- sum(state_stats$mail_sent_req_2020_npa) 
US_accept_party[5,4] <- sum(state_stats$mail_sent_req_2020_dem)+sum(state_stats$mail_sent_req_2020_rep)+sum(state_stats$mail_sent_req_2020_minor)+sum(state_stats$mail_sent_req_2020_npa) 

US_accept_party$Frequency <- 100*US_accept_party$Count/US_accept_party[5,2]
US_accept_party$Rate <- 100*US_accept_party$Count/US_accept_party$Count2

colnames(US_accept_party) <- c("Party", "Returned Ballots", "Freq. Distribution", "Requested Ballots", "Return Rate")

US_out_party <- party_shell_returned

US_out_party[1,2] <- sum(state_stats$mail_sent_req_2020_dem) - sum(state_stats$mail_accept_2020_dem) 
US_out_party[2,2] <- sum(state_stats$mail_sent_req_2020_rep) - sum(state_stats$mail_accept_2020_rep) 
US_out_party[3,2] <- sum(state_stats$mail_sent_req_2020_minor) - sum(state_stats$mail_accept_2020_minor)
US_out_party[4,2] <- sum(state_stats$mail_sent_req_2020_npa) - sum(state_stats$mail_accept_2020_npa) 
US_out_party[5,2] <- (sum(state_stats$mail_sent_req_2020_dem)+sum(state_stats$mail_sent_req_2020_rep)+sum(state_stats$mail_sent_req_2020_minor)+sum(state_stats$mail_sent_req_2020_npa)) - (sum(state_stats$mail_accept_2020_dem)+sum(state_stats$mail_accept_2020_rep)+sum(state_stats$mail_accept_2020_minor)+sum(state_stats$mail_accept_2020_npa))

US_out_party[1,5] <- sum(state_stats$mail_sent_req_2020_dem) 
US_out_party[2,5] <- sum(state_stats$mail_sent_req_2020_rep) 
US_out_party[3,5] <- sum(state_stats$mail_sent_req_2020_minor)
US_out_party[4,5] <- sum(state_stats$mail_sent_req_2020_npa) 
US_out_party[5,5] <- sum(state_stats$mail_sent_req_2020_dem)+sum(state_stats$mail_sent_req_2020_rep)+sum(state_stats$mail_sent_req_2020_minor)+sum(state_stats$mail_sent_req_2020_npa) 

US_out_party[1,4] <- sum(state_stats$mail_accept_2020_dem) 
US_out_party[2,4] <- sum(state_stats$mail_accept_2020_rep) 
US_out_party[3,4] <- sum(state_stats$mail_accept_2020_minor)
US_out_party[4,4] <- sum(state_stats$mail_accept_2020_npa) 
US_out_party[5,4] <- sum(state_stats$mail_accept_2020_dem)+sum(state_stats$mail_accept_2020_rep)+sum(state_stats$mail_accept_2020_minor)+sum(state_stats$mail_accept_2020_npa)

US_out_party$Frequency <- 100*US_out_party$Count/US_out_party[5,2]

colnames(US_out_party) <- c("Party", "Outstanding Ballots", "Freq. Distribution", "Returned Ballots", "Requested Ballots")

# Voted

US_voted_party <- party_shell

US_voted_party[1,2] <- sum(state_stats$mail_accept_2020_dem) + sum(state_stats$inperson_2020_dem)
US_voted_party[2,2] <- sum(state_stats$mail_accept_2020_rep) + sum(state_stats$inperson_2020_rep)
US_voted_party[3,2] <- sum(state_stats$mail_accept_2020_minor) + sum(state_stats$inperson_2020_minor)
US_voted_party[4,2] <- sum(state_stats$mail_accept_2020_npa) + sum(state_stats$inperson_2020_npa)
US_voted_party[5,2] <- sum(state_stats$mail_accept_2020_dem)+sum(state_stats$mail_accept_2020_rep)+sum(state_stats$mail_accept_2020_minor)+sum(state_stats$mail_accept_2020_npa) + sum(state_stats$inperson_2020_dem)+sum(state_stats$inperson_2020_rep)+sum(state_stats$inperson_2020_minor)+sum(state_stats$inperson_2020_npa)

US_voted_party$Percent <- 100*US_voted_party$Count/US_voted_party[5,2]

# Inperson

US_inperson_party <- party_shell

US_inperson_party[1,2] <- sum(state_stats$inperson_2020_dem) 
US_inperson_party[2,2] <- sum(state_stats$inperson_2020_rep) 
US_inperson_party[3,2] <- sum(state_stats$inperson_2020_minor)
US_inperson_party[4,2] <- sum(state_stats$inperson_2020_npa) 
US_inperson_party[5,2] <- sum(state_stats$inperson_2020_dem)+sum(state_stats$inperson_2020_rep)+sum(state_stats$inperson_2020_minor)+sum(state_stats$inperson_2020_npa)

US_inperson_party$Percent <- 100*US_inperson_party$Count/US_inperson_party[5,2]

NM_inperson_party <- party_shell

NM_inperson_party[1,2] <- state_stats[32,77] 
NM_inperson_party[2,2] <- state_stats[32,78] 
NM_inperson_party[3,2] <- state_stats[32,79] 
NM_inperson_party[4,2] <- state_stats[32,80] 
NM_inperson_party[5,2] <- state_stats[32,7] 

NM_inperson_party$Percent <- 100*NM_inperson_party$Count/NM_inperson_party[5,2]

NM_accept_party <- party_shell_returned

NM_accept_party[1,2] <- state_stats[32,29] 
NM_accept_party[2,2] <- state_stats[32,30] 
NM_accept_party[3,2] <- state_stats[32,31] 
NM_accept_party[4,2] <- state_stats[32,32] 
NM_accept_party[5,2] <- state_stats[32,6] 

NM_accept_party[1,4] <- state_stats[32,10] 
NM_accept_party[2,4] <- state_stats[32,11] 
NM_accept_party[3,4] <- state_stats[32,12] 
NM_accept_party[4,4] <- state_stats[32,13] 
NM_accept_party[5,4] <- state_stats[32,5] 

NM_accept_party$Frequency <- 100*NM_accept_party$Count/NM_accept_party[5,2]
NM_accept_party$Rate <- 100*NM_accept_party$Count/NM_accept_party$Count2

colnames(NM_accept_party) <- c("Party", "Returned Ballots", "Freq. Distribution", "Requested Ballots", "Return Rate")

NC_inperson_party <- party_shell

NC_inperson_party[1,2] <- state_stats[34,77] 
NC_inperson_party[2,2] <- state_stats[34,78] 
NC_inperson_party[3,2] <- state_stats[34,79] 
NC_inperson_party[4,2] <- state_stats[34,80] 
NC_inperson_party[5,2] <- state_stats[34,7] 

NC_inperson_party$Percent <- 100*NC_inperson_party$Count/NC_inperson_party[5,2]

NC_accept_party <- party_shell_returned

NC_accept_party[1,2] <- state_stats[34,29] 
NC_accept_party[2,2] <- state_stats[34,30] 
NC_accept_party[3,2] <- state_stats[34,31] 
NC_accept_party[4,2] <- state_stats[34,32] 
NC_accept_party[5,2] <- state_stats[34,6] 

NC_accept_party[1,4] <- state_stats[34,10] 
NC_accept_party[2,4] <- state_stats[34,11] 
NC_accept_party[3,4] <- state_stats[34,12] 
NC_accept_party[4,4] <- state_stats[34,13] 
NC_accept_party[5,4] <- state_stats[34,5] 

NC_accept_party$Frequency <- 100*NC_accept_party$Count/NC_accept_party[5,2]
NC_accept_party$Rate <- 100*NC_accept_party$Count/NC_accept_party$Count2

colnames(NC_accept_party) <- c("Party", "Returned Ballots", "Freq. Distribution", "Requested Ballots", "Return Rate")

LA_inperson_party <- party_shell

LA_inperson_party[1,2] <- state_stats[19,77] 
LA_inperson_party[2,2] <- state_stats[19,78] 
LA_inperson_party[3,2] <- state_stats[19,79] 
LA_inperson_party[4,2] <- state_stats[19,80] 
LA_inperson_party[5,2] <- state_stats[19,7] 

LA_inperson_party$Percent <- 100*LA_inperson_party$Count/LA_inperson_party[5,2]

FL_inperson_party <- party_shell

FL_inperson_party[1,2] <- state_stats[10,77] 
FL_inperson_party[2,2] <- state_stats[10,78] 
FL_inperson_party[3,2] <- state_stats[10,79] 
FL_inperson_party[4,2] <- state_stats[10,80] 
FL_inperson_party[5,2] <- state_stats[10,7] 

FL_inperson_party$Percent <- 100*FL_inperson_party$Count/FL_inperson_party[5,2]


FL_voted_party <- party_shell

FL_voted_party[1,2] <- state_stats[10,77] + state_stats[10,29] 
FL_voted_party[2,2] <- state_stats[10,78] + state_stats[10,30] 
FL_voted_party[3,2] <- state_stats[10,79] + state_stats[10,31]
FL_voted_party[4,2] <- state_stats[10,80] + state_stats[10,32] 
FL_voted_party[5,2] <- state_stats[10,7] + state_stats[10,6]

FL_voted_party$Percent <- 100*FL_voted_party$Count/FL_voted_party[5,2]

FL_return_party <- party_shell_returned

FL_return_party[1,2] <- state_stats[10,29] 
FL_return_party[2,2] <- state_stats[10,30] 
FL_return_party[3,2] <- state_stats[10,31] 
FL_return_party[4,2] <- state_stats[10,32] 
FL_return_party[5,2] <- state_stats[10,6] 

FL_return_party[1,4] <- state_stats[10,10] 
FL_return_party[2,4] <- state_stats[10,11] 
FL_return_party[3,4] <- state_stats[10,12] 
FL_return_party[4,4] <- state_stats[10,13] 
FL_return_party[5,4] <- state_stats[10,5] 

FL_return_party$Frequency <- 100*FL_return_party$Count/FL_return_party[5,2]
FL_return_party$Rate <- 100*FL_return_party$Count/FL_return_party$Count2

colnames(FL_return_party) <- c("Party", "Returned Ballots", "Freq. Distribution", "Requested Ballots", "Return Rate")


```

## **Record Overall Turnout?**

It appears likely that around 100 million early votes will be cast by the time Tuesday morning reports are processed. These reports will include early voting activity from the proceeding day. It is also likely reports by Tuesday morning will fail to capture all of the pre-election voting activity since there are sporadic reports of election officials experiencing delays in processing the unprecedented number of mail ballots. Furthermore, many states continue to accept mail ballots if they are postmarked on or before Election Day, as noted in this [New York Times article](https://www.nytimes.com/interactive/2020/10/27/upshot/election-results-timing.html). This report does not accurately describe mail ballot return deadlines for military and overseas civilian voters, which can be later than domestic voters.

What does this mean for overall turnout, including Election Day voters?

Before answering this question, let me first reiterate something very important about how to make forecasts with these data. The approach I use is known as difference-in-difference. In the election context, this technique makes a comparison to a past comparable election and then forecasts based on the current election. 

For example, in 2016 40% of the vote was cast early (this is a reasonable estimate of all early voting activity in 2016). If nothing changed, knowing the current estimate of 100 million early votes we could forecast 100 million/40% = 250 million votes will be cast in the election. Now, that is a ridiculously high number and we will not come close since it would be higher than the 239 million people [I estimate](http://www.electproject.org/2020g) are eligible to vote!

The obvious reason why an estimate of 40% of the vote will be cast early is wrong is that something changed. The difference-in-difference approach works best where there is a good comparison point. Does this mean that things are so different than 2016 that we cannot know anything from the early vote? No. There are some states where there is a good past comparison because they did not change their elections significantly or where we can make educated guesses about what the early vote is telling us relative to 2016.

One strong signal is that turnout will be higher than in 2016, because some states have already exceeded their 2016 turnout or are close to doing so.

| State         | % 2016 Total Vote |
| ------------- |-------------:|
| Hawaii         | 111% |
| Texas         | 108% |
| Montana       | 99% |
| North Carolina | 95% |
| Georgia | 94% |
| New Mexico | 93% |
| Nevada | 91% |
| Tennessee |90% |
| Oregon | 88% |
| Colorado | 87% |
| Arizona | 87% |
| New Jersey | 80% |

To forecast the 2020 turnout, the big unknowns are (in temporal order):

* How many early votes are left to be cast?
* How much Election Day vote there will be? 
* How many legally cast mail ballots postmarked on or before Election Day will arrive afterwards (which depends on states' ballot return deadlines)? 

I've been [saying for over a year](https://www.theatlantic.com/politics/archive/2019/06/2020-election-voter-turnout-could-be-record-breaking/591607/) that 2020 could see record turnout for a modern election. More recently, I've been using a 150 million turnout estimate as a shorthand to convey that this number is just that, an estimate. Now that more early vote data are available, I'm ready to make a more concrete prediction.

Examining each state in turn, and rolling up the state estimates to a national estimate, I arrive at a total turnout rate of 160.2 million votes, or a turnout rate for those [eligible to vote](http://www.electproject.org/2020g) of 67.0%.

Regrettably, I have signed a non-disclosure agreement with the national exit poll organization that prevents me from going into greater detail about state turnout estimates, as I have in past years. I will be allowed to post estimates late on election night, which I will continue to update in the days afterwards as results are reported. Trust me, no one is more disappointed than me about this situation.

## **Who Will Win?**

I know you could care less about a turnout prediction. What you really want to know is who will win.

For the most part, the clues come from states that have party registration. The difference-in-difference approach can be applied by examining the difference in the percentage of early voters in 2016 registered with the Democratic and Republican Parties and comparing the party registration difference to 2020.

The caveats that apply to forecasting turnout, also apply to forecasting who will win, with an additional caveat:

* We cannot know with certainty the vote preferences of registered Democrats, Republicans, or non-affiliated voters.

Surveys are the best source of this latter information. For those who say surveys are the only source for forecasting election outcomes, I would point out that some survey samples are drawn from lists of registered voters and are weighted to party registration breakdowns. These pollsters implicitly believe there is value to party registration data.

I believe that the party registration breakdowns of early voters can provide clues not only to the partisan composition of the electorate, but also to the relative enthusiasm of Democrats and Republicans to vote. If there is an electoral swing towards a candidates of a political party, some of that swing should be evident in relative enthusiasm to vote (early).

Again, the big caution is that early voting has changed so much from 2016 in many states, that there is no good past comparison; a key assumption of the difference-in-difference approach.

There are certain states that did not change the way they run their elections: the all-mail ballot states. Let's start with analyzing three in particular: Colorado, Oregon, and Nevada (which had a large amount of early vote in 2016). These provide us with the best 2016 comparison.

**Colorado**

Colorado is not a battleground state, so it will not be bold for me to predict Biden will win. He will. That said, Republican Senator Cory Gardner looks to be in deep trouble. Let's look at the [Colorado data](https://electproject.github.io/Early-Vote-2020G/CO.html) to understand why:


| Party         | % 2020 Early Vote  | % 2016 Early Vote  | % 2016 Actual Vote  |
| ------------- |-------------:|-------------:|-------------:|
| Democrats     | 33.8% | 34.0% | 48.2% |
| Republicans   | 28.0% | 34.8% | 43.3% |
| Dem Lead    | +5.8 | -0.2 | +4.9 | 

In 2016, Hillary Clinton won Colorado by 4.9 percentage points, despite registered Republicans having a slight 0.2 percentage point advantage among the electorate in the final [Election Day report](https://content.govdelivery.com/attachments/COSOS/2016/11/08/file_attachments/655240/Ballots%2BReceived%2Bto%2BDate_20161108.pdf) of from the Secretary of State's office. If you just look at the early vote, there is currently a 6 point shift in the party registration breakdown of the state towards the Democrats. 

If candidate preferences haven't changed, it is virtually impossible for Trump to win Colorado. He would need sizable defections from registered Democrats and a big swing among those not affiliated with a political party to win. The preponderance of the polling evidence does not support either possibility. 

These party differences are not just a product of a changing Colorado electorate. Registered Democrats are returning their mail ballots at a much higher rate that registered Republicans, 70.1% to 63.6% (at the time of this writing.) This speaks to a relative enthusiasm gap. If Trump voters are too shy to talk to pollsters, they are also too shy to vote. Maybe Republicans become embolded by Election Day. Maybe they vote in-person, since Colorado provides opportunities to cast ballots at vote centers, which are essentially super-polling locations. So far, only a little less than 40 thousand people have cast in-person votes. Trump (and really Senator Gardner) will need massive turnout on Election Day to make up the deficit. Anything is possible, but it this seems a remote possibility.

**Oregon**

Oregon is even less of a battleground than Colorado, so it will come as no surprise that Biden appears likely to win Oregon. But, there are shifts in the partisan composition of the electorate that mirror those in Colorado. These [Oregon data](https://electproject.github.io/Early-Vote-2020G/OR.html) are a little more stale than Colorado, having been last updated on Friday, but they should be a fairly good snapshot of where Oregon stands.

| Party         | % 2020 Early Vote  | % 2016 Early Vote  | % 2016 Actual Vote  |
| ------------- |-------------:|-------------:|-------------:|
| Democrats     | 43.5% | 44.7% | 50.1% |
| Republicans   | 28.0% | 32.6% | 39.1% |
| Dem Lead    | +15.5 | +12.1 | +11.0 | 

Like Colorado, there has been a marked shift in the partisan composition of the electorate towards the Democrats. Indeed, we can also infer in both states those not affiliated with a political party, or aligned with a minor party, are also a greater share of the electorate than in 2016 since the percentages of those registered with a political party declined across Colorado and Oregon. (If there will be a high turnout election, those persons with weaker partisan attachments would be expected to vote in higher numbers.)

Again, I'm not interested in predicting who will win these states since they are not battlegrounds. The point of interest in both states is we see a shift in the party composition of the electorate towards the Democrats. This is consistent with the polling showing Biden performing better than Clinton. We might thus have greater confidence that the polling showing a Biden lead is sending a true signal.

**Nevada**

Nevada is an all-mail state in 2020, but it was not an all-mail ballot state in 2016. A little more than 2/3rds of its votes were cast before Election Day in 2016, so there might be a reasonable comparison to be made. For these statistics, I'm including in my [Nevada data](https://electproject.github.io/Early-Vote-2020G/NV.html) a large Clark County mail ballot report that I downloaded on Sunday that is not yet reflected in the state reports, and that Nevada reporter Jon Ralston [believes is key](https://thenevadaindependent.com/article/the-early-voting-blog-3) to a Biden win.

| Party         | % 2020 Early Vote  | % 2016 Early Vote  | % 2016 Actual Vote  |
| ------------- |-------------:|-------------:|-------------:|
| Democrats     | 40.3% | 42.1% | 47.9% |
| Republicans   | 35.9% | 36.2% | 45.5% |
| Dem Lead    | +4.4 | +5.9 | +2.9 | 

Here, the early vote data suggests that Biden will eek out a very narrow win in Nevada, with a shift of 1.5 percentage points in the partisan distribution of the electorate. But, what is also suggestive in these data is that Trump made up ground on Election Day in 2016. This is the primarily forecasting confound for the all the other states. The past election is not the same, and comparisons must be made carefully. Most likely, Nevada will not see the same Election Day vote as in 2016. If it did, it would have a turnout rate off the charts, perhaps even higher than Colorado or Oregon. That seems unlikely. Most likely, the Election Day vote might be closer to, say, a quarter of the overall electorate. If this is the case, then there is less gas in the tank for Trump to roll to victory on the strength of the Election Day vote.

Another factor present in Nevada is that there are more voters not aligned with the major political parties among the early voters. Again, this is expected if we are to have a high turnout election. All things equal, the percentage margin between the two major parties is reduced due to the increase of unaffiliated voters.

On the early vote alone, it appears that Biden will win Nevada. It could be close. [The Real Clear Politics Nevada average](https://www1.realclearpolitics.com/epolls/2020/president/Nevada.html) has a +3.6 point Biden lead, which seems in line with the early vote.

**Florida**

Florida looks darn close, again.

| Party         | % 2020 Early Vote  | % 2016 Early Vote  | % 2016 Actual Vote  |
| ------------- |-------------:|-------------:|-------------:|
| Democrats     | 39.2% | 39.8% | 47.8% |
| Republicans   | 38.1% | 38.3% | 49.0% |
| Dem Lead    | +1.1 | +1.5 | -1.2 | 

At first blush, the numbers are bullish for Trump. Republicans are doing slightly better in the partisan distribution of the 2020 early vote than in 2016, in a state Trump won narrowly in 2016.

But, there are two factors suggesting these [Florida data](https://electproject.github.io/Early-Vote-2020G/FL.html) are sending too bullish of a signal. 

First, as in-person early voting has ended, Democrats should build on their early vote lead on the strength of additional mail ballots to be returned, which are expected todecidedly break Democratic.

Second, like Nevada, there is only so much more Election Day vote possible. In 2016, only 40% of Florida's vote was cast early. We're probably looking somewhere around 75% of Florida's vote cast early, unless Florida will have astronomical turnout unlike anything ever seen before in any state in modern times. That isn't supported in the early vote we're seeing so far elsewhere, and it would be very odd to see a huge turnout spike localized in a single state. 

So, there is a lot of uncertainty. I think Florida is close, but there is no real way to determine which candidate is favored with the large unknown of the size of the Election Day vote. Of course, [the polls](https://www.realclearpolitics.com/epolls/2020/president/fl/florida_trump_vs_biden-6841.html) are telling us the same thing. Florida is close.

**North Carolina**

Trump appears to be in a better position in North Carolina than Florida.  

| Party         | % 2020 Early Vote  | % 2016 Early Vote  | % 2016 Actual Vote  |
| ------------- |-------------:|-------------:|-------------:|
| Democrats     | 37.4% | 41.7% | 46.2% |
| Republicans   | 31.7% | 31.9% | 49.8% |
| Dem Lead    | +5.7 | +9.8 | -3.6 | 

The North Carolina Board of Elections also provides data on the partisan composition of the entire 2016 electorate.

| Party         | % 2016 All Voters  |
| ------------- |-------------:|
| Democrats     | 39.3% |
| Republicans   | 32.0% |
| Dem Lead    | +7.3 | 

Unlike Florida, Biden cannot rely on an unknown smaller size of the Election Day vote to bolster his chances, since the Election Day vote is expected to be very Republican. He will have to rely on voters' changing preferences. Also, note like before there are more unaffiliated voters among early voters in 2020. These, too, will be a key if Biden is to flip North Carolina. [The polls](https://www.realclearpolitics.com/epolls/2020/president/nc/north_carolina_trump_vs_biden-6744.html) have North Carolina very close, closer than Florida, which is supported by the early voting data. If anything, the early voting data alone are pointing to a Trump win.

**Maine**

Biden appears to be well-positioned to win Maine. Again, this is not a surprise since [Biden is polling strongly in Maine](https://www.realclearpolitics.com/epolls/2020/president/Maine.html). The strong Democratic performance in the early vote is probably more consequential to the Senate race.


| Party         | % 2020 Early Vote  | % 2016 Early Vote  | % 2016 Actual Vote  |
| ------------- |-------------:|-------------:|-------------:|
| Democrats     | 48.1% | 40.5% | 47.8% |
| Republicans   | 23.7% | 27.0% | 44.9% |
| Dem Lead    | +24.4 | +13.5 | +2.9 | 

What may help Senator Collins is that I expect a much larger share of the electorate to vote on Election Day -- perhaps as much as 40% -- than in Florida or North Carolina. She will need a incredibly strong Republican presence on Election Day to help her with a surprise win, [according to the polls](https://www.realclearpolitics.com/epolls/2020/senate/me/maine_senate_collins_vs_gideon-6928.html).

**Iowa**

Ah, Iowa. The state [I missed the most in my 2016 forecast](https://www.huffpost.com/entry/early-vote-election-eve-p_b_12853864). If at first you don't succeed, try, try, again.

| Party         | % 2020 Early Vote  | % 2016 Early Vote  | % 2016 Actual Vote  |
| ------------- |-------------:|-------------:|-------------:|
| Democrats     | 46.4% | 41.3% | 41.7% |
| Republicans   | 33.0% | 34.6% | 51.2% |
| Dem Lead    | +13.4 | +6.7 | -9.5 | 

While the early vote looks good for Biden, he can't count on the signal from it alone, as he would make up only 6.7 points on his 9.5 point loss (yes, there is rounding error in there since Trump's actual margin was 9.4 points...I have the choice of having people telling me the numbers don't add up, or people telling me I don't have the right margin because it's off by a tenth of a percentage point.)

Like Maine, I expect there to be a sizable Election Day vote, perhaps as much as 50% of the total. So, there is more gas in the Election Day tank for Republicans in Iowa. 

The [Iowa polls average](https://www.realclearpolitics.com/epolls/2020/president/Iowa.html) point to a narrow Trump win. I think the *Des Moines Register* poll is probably a little too bullish on Trump, but due to random sampling error it makes sense we'd get an outlier poll like it if Trump had a slight Iowa lead, which is what the early vote suggests. Again, like Maine, there is a lot of uncertainty here about the size of the Election Day vote which will likely be very Republican, even more so than other states. 

**Arizona**

The [Arizona data](https://electproject.github.io/Early-Vote-2020G/AZ.html) is signaling a Biden win, but I'm very cautious about this because party registration is not quite the same here as elsewhere. Party registration is [applied only to presidential elections](https://azsos.gov/elections), whereas the state has semi-open primaries for all other primary elections. With only Democrats holding a contested primary in 2020, it may be that the changes in party registration of the early vote is sending too bullish of a signal. Still, here are the numbers.

| Party         | % 2020 Early Vote  | % 2016 Early Vote  | % 2016 Actual Vote  |
| ------------- |-------------:|-------------:|-------------:|
| Democrats     | 38.2% | 33.6% | 45.1% |
| Republicans   | 36.3% | 40.0% | 48.7% |
| Dem Lead    | +1.9 | -6.4 | -3.6 | 

It doesn't seem possible that there could be a 8.3 point shift in Arizona. [The polls](https://www.realclearpolitics.com/epolls/2020/president/az/arizona_trump_vs_biden-6807.html) have the state much closer than that. I think the early vote is showing that Biden could indeed have a narrow lead, but it is probably overstating it.

Arizona is actually a heavy early voting state, much like Nevada. So the Election Day vote is probably less of a factor here than elsewhere, with perhaps only 15% or so of the vote to be cast on Election Day.

**Pennsylvania**

I'm not saying anything about Pennsylvania, a state with party registration. The state had excuse-required absentee voting in 2016, so there no comparison should be made to the partisan distribution of the small number of voters who cast absentee ballots in 2016 to the much larger number voting in 2020.

**Big Takeaways**

The early vote appears to confirm the polls that there has been a swing to the Democrats since 2016, which should benefit Biden. But, the swing is not uniform, and some of the closest states in 2016 -- Florida and North Carolina -- appear to be close again.

The early vote also is signaling that unaffiliated voters will be participating at higher rates than 2016. I should add that these voters are not the same as self-identified independents in polls. They are people who don't tend to vote in party primaries. They tend to be younger, and more often persons of color. These infrequent voters are exactly the sorts of people you'd expect to see engaged if there will be a high turnout election. Their larger presence in the electorate could make a significant contribution to the election outcome, beyond the simple partisan differences I'm discussing here to make my election forecasts.

## **Outstanding Mail Ballots**

If much concern to Democrats are all the mail ballots that have yet to be returned. These should be of concern, but I want to put these statistics in context.

As of this writing, there are **`r format(as.numeric(sum(state_stats$mail_sent_req_2020) - sum(state_stats$mail_accept_2020)), big.mark =",")`** outstanding mail ballots that have not been entered as returned by election officials.  

There are many unknowns with the outstanding mail ballots, so it is difficult to take these numbers at face value.

Factors in favor of the outstanding mail ballots being an over-count:

* Some mail ballots are in transit. 
* Some states continue to accept mail ballots if postmarked by Election Day.
* Some are at election offices but have not been entered into their databases. 
* It is unclear how election officials manage data for voters who requested a mail ballot, but decided to cast an in-person vote.

Factors in favor of the outstanding mail ballots being an under-count:

* Some states do not report mail ballot applications or the number of ballots sent; Texas probably being the largest of these states.
* Although not affecting the total number, the mail ballot return rate is too high in states where in-person votes are co-mingled with mail ballots; states like Iowa, among others.

Election officials in many states have never had to process so many mail ballots, so reporting delays and inconsistencies in reporting are understandable. When there were only tens of thousands of mail ballots statewide in some of these states, it was relatively easy to process the ballots and no one really cared about the few where someone may vote in-person. Increase the workload by two orders of magnitude, and delays will happen. Add to this the uncertainties with the post office driving more people to decide to vote in-person. We're making do in tough times with a poorly-funded election infrastructure in many places.

I believe on balance that there are more returned ballots than reflected in my tracking. How many, I cannot say.