---
title: "Kansas Early Voting Statistics"
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(knitr)
library(kableExtra)
library(scales)
library(DT)
library(highcharter)

state_stats <- read_csv("D:/DropBox/Dropbox/Mail_Ballots_2020/markdown/2020G_Early_Vote.csv")

# Setup

party_shell <- data.frame(Party=character(),
                                  Count=integer(),
                                  Percent=double(),
                                  stringsAsFactors=FALSE)
party_shell[1,1] <- "Democrats"
party_shell[2,1] <- "Republicans"
party_shell[3,1] <- "Minor"
party_shell[4,1] <- "No Party Affiliation"
party_shell[5,1] <- "TOTAL"


party_shell_returned <- data.frame(Party=character(),
                                  Count=integer(),
                                  Frequency=double(),
                                  Count2=integer(),
                                  Rate=integer(),
                                  stringsAsFactors=FALSE)
party_shell_returned[1,1] <- "Democrats"
party_shell_returned[2,1] <- "Republicans"
party_shell_returned[3,1] <- "Minor"
party_shell_returned[4,1] <- "No Party Affiliation"
party_shell_returned[5,1] <- "TOTAL"


gender_shell <- data.frame(Gender=character(),
                                  Count=integer(),
                                  Percent=double(),
                                  stringsAsFactors=FALSE)
gender_shell[1,1] <- "Female"
gender_shell[2,1] <- "Male"
gender_shell[3,1] <- "Unknown"
gender_shell[4,1] <- "TOTAL"

age_shell <- data.frame(Age=character(),
                                  Count=integer(),
                                  Percent=double(),
                                  stringsAsFactors=FALSE)
age_shell[1,1] <- "18 to 24"
age_shell[2,1] <- "25 to 34"
age_shell[3,1] <- "35 to 44"
age_shell[4,1] <- "45 to 54"
age_shell[5,1] <- "55 to 64"
age_shell[6,1] <- "65 and up"
age_shell[7,1] <- "TOTAL"

# Oklahoma

KS_req_send_party <- party_shell

KS_req_send_party[1,2] <- state_stats[17,10] 
KS_req_send_party[2,2] <- state_stats[17,11] 
KS_req_send_party[3,2] <- state_stats[17,12] 
KS_req_send_party[4,2] <- state_stats[17,13] 
KS_req_send_party[5,2] <- state_stats[17,5] 

KS_req_send_party$Percent <- 100*KS_req_send_party$Count/KS_req_send_party[5,2]

KS_accept_party <- party_shell_returned

KS_accept_party[1,2] <- state_stats[17,29] 
KS_accept_party[2,2] <- state_stats[17,30] 
KS_accept_party[3,2] <- state_stats[17,31] 
KS_accept_party[4,2] <- state_stats[17,32] 
KS_accept_party[5,2] <- state_stats[17,6] 

KS_accept_party[1,4] <- state_stats[17,10] 
KS_accept_party[2,4] <- state_stats[17,11] 
KS_accept_party[3,4] <- state_stats[17,12] 
KS_accept_party[4,4] <- state_stats[17,13] 
KS_accept_party[5,4] <- state_stats[17,5] 

KS_accept_party$Frequency <- 100*KS_accept_party$Count/KS_accept_party[5,2]
KS_accept_party$Rate <- 100*KS_accept_party$Count/KS_accept_party$Count2

colnames(KS_accept_party) <- c("Party", "Returned Ballots", "Freq. Distribution", "Requested Ballots", "Return Rate")


```
## {.tabset}
Last Report: `r state_stats[17,9]`  
Source:  `r state_stats[17,2]`

Total Early Votes: **`r format(as.numeric(state_stats[17,8]), big.mark =",")`**

### Mail Ballots Returned

Ballots Returned: **`r format(as.numeric(state_stats[17,6]), big.mark =",")`**

#### **Mail Ballots Returned and Accepted by Party Registration**

``` {r echo = FALSE}
kable(KS_accept_party, format.args = list(big.mark = ",", 
  scientific = FALSE), digits = 1) %>%
  kable_styling(bootstrap_options = "striped", full_width = F, position = "left")
```

### Requested Mail Ballots

Ballots Requested: **`r format(as.numeric(state_stats[17,5]), big.mark =",")`**
