---
title: "Montana Early Voting Statistics"
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(knitr)
library(kableExtra)
library(scales)
library(DT)
library(highcharter)

state_stats <- read_csv("D:/DropBox/Dropbox/Mail_Ballots_2020/markdown/2020G_Early_Vote.csv")

MT_stats <- read_csv("D:/DropBox/Dropbox/Mail_Ballots_2020/markdown/2020G_Early_Vote_MT.csv")

# Setup

party_shell <- data.frame(Party=character(),
                                  Count=integer(),
                                  Percent=double(),
                                  stringsAsFactors=FALSE)
party_shell[1,1] <- "Democrats"
party_shell[2,1] <- "Republicans"
party_shell[3,1] <- "Minor"
party_shell[4,1] <- "No Party Affiliation"
party_shell[5,1] <- "TOTAL"

race_shell <- data.frame(Race=character(),
                                  Count=integer(),
                                  Percent=double(),
                                  stringsAsFactors=FALSE)
race_shell[1,1] <- "Non-Hispanic White"
race_shell[2,1] <- "Non-Hispanic Black"
race_shell[3,1] <- "Hispanic"
race_shell[4,1] <- "Non-Hispanic Asian American"
race_shell[5,1] <- "Non-Hispanic Native American"
race_shell[6,1] <- "Other/Multiple/Unknown"
race_shell[7,1] <- "TOTAL"


gender_shell <- data.frame(Gender=character(),
                                  Count=integer(),
                                  Percent=double(),
                                  stringsAsFactors=FALSE)
gender_shell[1,1] <- "Female"
gender_shell[2,1] <- "Male"
gender_shell[3,1] <- "Unknown"
gender_shell[4,1] <- "TOTAL"

age_shell <- data.frame(Age=character(),
                                  Count=integer(),
                                  Percent=double(),
                                  stringsAsFactors=FALSE)
age_shell[1,1] <- "18 to 24"
age_shell[2,1] <- "25 to 34"
age_shell[3,1] <- "35 to 44"
age_shell[4,1] <- "45 to 54"
age_shell[5,1] <- "55 to 64"
age_shell[6,1] <- "65 and up"
age_shell[7,1] <- "TOTAL"

# Montana

MT_req_send_tot <- data.frame(Total=character(),
                                  Count=integer(),
                                  Percent=double(),
                                  stringsAsFactors=FALSE)

MT_req_send_tot[1,1] <- "TOTAL"
MT_req_send_tot[1,2] <- sum(state_stats[27,5]) 

MT_req_send_tot$Percent <- 100.0

MT_stats <- mutate(MT_stats, Pct.Return =  Mail.Rtn.Tot/Mail.Req.Tot)

MT_stats_returns <- select(MT_stats, County.Name, Mail.Rtn.Tot, Mail.Req.Tot, Pct.Return)

```
## {.tabset}
Last Report: `r state_stats[27,9]`  
Source:  `r state_stats[27,2]`

### Returned Mail Ballots

Mail Ballots Returned: **`r format(as.numeric(state_stats[27,6]), big.mark =",")`**

``` {r echo = FALSE}

MT_2020g_map_data <- MT_stats

MT_2020g_map_data$fips <- as.character(MT_2020g_map_data$fips)

MT_2020g_map_data <- mutate(MT_2020g_map_data, percent = round(100*Pct.Return, digits = 1))

mapfile <- download_map_data("countries/us/us-mt-all.js")
mapdata <- get_data_from_map(mapfile)

mapdata$row <- as.integer(rownames(mapdata))

MT_2020g_map_data <- left_join(MT_2020g_map_data, mapdata, by = "fips")

MT_2020g_map_data <- arrange(MT_2020g_map_data, row)

hcmap(map = "countries/us/us-mt-all", data = MT_2020g_map_data,
  value = "percent", name = "Percent Returned", joinBy = "fips") %>%
  hc_title(text ="Mail Ballot Return Rates") %>%
  hc_subtitle(text = "County plots may not be shaded using the same scale")
```

``` {r echo = FALSE}
datatable(MT_stats_returns, colnames = c("County", "Mail Ballots Returned", "Mail Ballots Sent", "Percent Returned"), rownames = F) %>%
  formatPercentage('Pct.Return', 1) %>%
  formatRound(c('Mail.Rtn.Tot','Mail.Req.Tot'), 0, mark = ",")
```


### Mail Ballots Sent

Mail Ballots Sent: **`r format(as.numeric(state_stats[27,5]), big.mark =",")`**
